# Generated by Django 3.2.3 on 2023-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('name', 'owner', 'birth_year'), name='unique_name_owner_birth_year'),
        ),
    ]
